"""Updated username/email length

Revision ID: 3e31c530e23b
Revises: e72c83c35dc8
Create Date: 2025-01-05 18:32:37.899977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e31c530e23b'
down_revision = 'e72c83c35dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_table')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    op.create_table('budget_table',
    sa.Column('entry_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expected_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expected_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('actual_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cleared', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('not_expected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('entry_id', name='budget_table_pkey')
    )
    # ### end Alembic commands ###
