"""Initial migration.

Revision ID: 9340fceb1266
Revises: 
Create Date: 2024-11-30 20:26:48.093993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9340fceb1266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('expenses_income_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('expenses_bill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'incomes', ['income_id'], ['id'])
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['id'])
        op.add_column('incomes', sa.Column('day', sa.String(10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('expenses_bill_id_fkey', 'bills', ['bill_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('expenses_income_id_fkey', 'incomes', ['income_id'], ['id'], ondelete='SET NULL')
        op.drop_column('incomes', 'day')

    # ### end Alembic commands ###
