"""Added linked_id column to expense table, removed bill_id and income_id

Revision ID: acca45db5922
Revises: b4c765eda2b6
Create Date: 2024-12-02 15:46:56.287232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acca45db5922'
down_revision = 'b4c765eda2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('expenses_income_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('expenses_bill_id_fkey', type_='foreignkey')
        batch_op.drop_column('bill_id')
        batch_op.drop_column('income_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('expenses_bill_id_fkey', 'bills', ['bill_id'], ['id'])
        batch_op.create_foreign_key('expenses_income_id_fkey', 'incomes', ['income_id'], ['id'])
        batch_op.drop_column('linked_id')

    # ### end Alembic commands ###
