"""fixed day of the week

Revision ID: b4c765eda2b6
Revises: de919d30a904
Create Date: 2024-11-30 21:13:52.189351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c765eda2b6'
down_revision = 'de919d30a904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=10), nullable=True))
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
