"""added income columns.

Revision ID: de919d30a904
Revises: 9340fceb1266
Create Date: 2024-11-30 21:04:07.658810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de919d30a904'
down_revision = '9340fceb1266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###
